name: opv2v_pnpda_protocol_pyramid_m1m2m3m4
root_dir: "dataset/OPV2V/train"
validate_dir: "dataset/OPV2V/validate"
test_dir: "dataset/OPV2V/test"

yaml_parser: "load_general_params"

train_setting:
  train_params:
    batch_size: 1
    epoches: 8
    eval_freq: 1
    save_freq: 1
    max_cav: 5

  optimizer:
    core_method: Adam
    lr: 0.001
    args:
      eps: 1e-10
      weight_decay: 1e-4

  lr_scheduler:
    core_method: multistep #step, multistep and Exponential support
    gamma: 0.1
    step_size: [10, 50, 80]



comm_range: 70
input_source: ['lidar', 'camera', 'depth']
label_type: 'lidar'
cav_lidar_range: &cav_lidar [-102.4, -51.2, -3, 102.4, 51.2, 1]

add_data_extension: ['bev_visibility.png']

heter:
  assignment_path: "opencood/logs/heter_modality_assign/opv2v_4modality.json" 
  ego_modality: &ego_modality "m1&m2&m3&m4"
  mapping_dict: &mapping_dict
    m1: m1
    m2: m3
    m3: m2
    m4: m4
  lidar_channels_dict:
    m3: 32
  modality_setting:
    m1:
      sensor_type: &sensor_type_m1 'lidar'
      core_method: &core_method_m1 "point_pillar"

      # lidar requires preprocess
      preprocess:
        # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
        core_method: 'SpVoxelPreprocessor'
        args:
          voxel_size: &voxel_size [0.4, 0.4, 4]
          max_points_per_voxel: 32
          max_voxel_train: 32000
          max_voxel_test: 70000
        # lidar range for each individual cav.
        cav_lidar_range: *cav_lidar
    m2:
      sensor_type: &sensor_type_m2 'camera'
      core_method: &core_method_m2 "lift_splat_shoot"

      grid_conf: &grid_conf_m2
        xbound: [-51.2, 51.2, 0.4]   # Limit the range of the x direction and divide the grids
        ybound: [-51.2, 51.2, 0.4]   # Limit the range of the y direction and divide the grids
        zbound: [-10, 10, 20.0]   # Limit the range of the z direction and divide the grids
        ddiscr: [2, 50, 48]
        mode: 'LID'
      data_aug_conf: &data_aug_conf_m2
        resize_lim: [0.65, 0.7]
        final_dim: [384, 512]
        rot_lim: [-3.6, 3.6]
        H: 600
        W: 800
        rand_flip: False
        bot_pct_lim: [0.0, 0.05]
        cams: ['camera0', 'camera1', 'camera2', 'camera3']
        Ncams: 4
    m3:
      sensor_type: &sensor_type_m3 'lidar'
      core_method: &core_method_m3 "second"

      # lidar requires preprocess
      preprocess:
        # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
        core_method: 'SpVoxelPreprocessor'
        args:
          voxel_size: &voxel_size_m3 [0.1, 0.1, 0.1]
          max_points_per_voxel: 5
          max_voxel_train: 32000
          max_voxel_test: 70000
        # lidar range for each individual cav.
        cav_lidar_range: *cav_lidar
    m4:
      sensor_type: &sensor_type_m4 'camera'
      core_method: &core_method_m4 "lift_splat_shoot"

      grid_conf: &grid_conf_m4
        xbound: [-51.2, 51.2, 0.4]   # Limit the range of the x direction and divide the grids
        ybound: [-51.2, 51.2, 0.4]   # Limit the range of the y direction and divide the grids
        zbound: [-10, 10, 20.0]   # Limit the range of the z direction and divide the grids
        ddiscr: [2, 50, 48]
        mode: 'LID'
      data_aug_conf: &data_aug_conf_m4
        resize_lim: [0.56, 0.61]
        final_dim: [336, 448]
        rot_lim: [-3.6, 3.6]
        H: 600
        W: 800
        rand_flip: False
        bot_pct_lim: [0.0, 0.05]
        cams: ['camera0', 'camera1', 'camera2', 'camera3']
        Ncams: 4


fusion:
  # core_method: 'intermediateheterpair'
  core_method: 'intermediatehetercontrastive'
  dataset: 'opv2v'
  args: 
    proj_first: false
    grid_conf: None # place-holder
    data_aug_conf: None # place-holder

data_augment: # no use in intermediate fusion
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: [0.4, 0.4, 4] # useful
    max_points_per_voxel: 1 # useless
    max_voxel_train: 1 # useless
    max_voxel_test: 1 # useless
  # lidar range for each individual cav.
  cav_lidar_range: *cav_lidar

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessorContrastive' # VoxelPostprocessor, BevPostprocessor supported
  # core_method: 'VoxelPostprocessor'
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 2
    num: &anchor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: 'hwl' # hwl or lwh
  max_num: 150 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

# model related
model:
  core_method: heter_pnpda_protocol
  args:
    supervise_single: true
    mapping_dict: *mapping_dict
    lidar_range: *cav_lidar

    pub:
      protocol_feat_dim: &protocol_dim 64
      granularity_H: &gra_H 0.8
      granularity_W: &gra_W 0.8

    m1:
      model_dir: stage0_m1_collab
      core_method: *core_method_m1
      sensor_type: *sensor_type_m1
      local_dim: &local_dim_m1 64

      encoder_args:
        voxel_size: *voxel_size
        lidar_range: *cav_lidar
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters: [64]
        point_pillar_scatter:
          num_features: 64

      backbone_args:
        layer_nums: [3]
        layer_strides: [2]
        num_filters: [64]
  
      aligner_args:
        core_method: identity

      adapter_args: 
        local_dim: *local_dim_m1
        local_range: *cav_lidar
        protocol_parameters:
          protocol_dim: *protocol_dim
          # Compute from: H_uni: 128, W_uni: 256; unify_range: [-102.4, -51.2, -3, 102.4, 51.2, 1]
          granularity_H: *gra_H
          granularity_W: *gra_W
        resizer:
          method: conv  # 通道数不一致时的对齐方式
          reduce_raito: 2 
        momentum_ratio: 0.8
        encoder:
          num_layers: 2
          num_heads: 8
          d_ff: 128
          d_model: *protocol_dim
          dropout: 0.2
        decoder:
          num_layers: 1
          num_heads: 8
          d_model: *local_dim_m1
          d_ff: 128
        
      fusion_net:
        method: pyramid
        args: 
          resnext: true
          layer_nums: [3, 5, 8]
          layer_strides: [1, 2, 2]
          num_filters: [64, 128, 256]
          upsample_strides: [1, 2, 4]
          num_upsample_filter: [128, 128, 128]
          anchor_number: *anchor_num

          shrink_header: 
            kernal_size: [ 3 ]
            stride: [ 1 ]
            padding: [ 1 ]
            dim: [ 256 ]
            input_dim: 384 # 128 * 3

      in_head: 256

      anchor_number: *anchor_num
      dir_args: *dir_args
    
    m2:
      model_dir: stage0_m2_collab
      core_method: *core_method_m2
      sensor_type: *sensor_type_m2
      local_dim: &local_dim_m2 64

      encoder_args:
        anchor_number: *anchor_num
        grid_conf: *grid_conf_m2
        data_aug_conf: *data_aug_conf_m2
        img_downsample: 8
        img_features: &img_feature 128
        use_depth_gt: false
        depth_supervision: true
        camera_encoder: EfficientNet

      camera_mask_args:
        cav_lidar_range: *cav_lidar
        grid_conf: *grid_conf_m2

      backbone_args:
        layer_nums: [3]
        layer_strides: [2]
        num_filters: [64]
        inplanes: 128

      aligner_args:
        core_method: identity

      adapter_args: 
        local_dim: *local_dim_m2
        local_range: *cav_lidar
        protocol_parameters:
          protocol_dim: *protocol_dim
          # Compute from: H_uni: 128, W_uni: 256; unify_range: [-102.4, -51.2, -3, 102.4, 51.2, 1]
          granularity_H: *gra_H
          granularity_W: *gra_W
        resizer:
          method: conv  # 通道数不一致时的对齐方式
          reduce_raito: 2 
        momentum_ratio: 0.8
        encoder:
          num_layers: 2
          num_heads: 8
          d_ff: 128
          d_model: *protocol_dim
          dropout: 0.2
        decoder:
          num_layers: 1
          num_heads: 8
          d_model: *local_dim_m2
          d_ff: 128

      fusion_net: 
        method: pyramid
        args:  
          resnext: true
          layer_nums: [3, 5, 8]
          layer_strides: [1, 2, 2]
          num_filters: [64, 128, 256]
          upsample_strides: [1, 2, 4]
          num_upsample_filter: [128, 128, 128]
          anchor_number: *anchor_num

          shrink_header: 
            kernal_size: [ 3 ]
            stride: [ 1 ]
            padding: [ 1 ]
            dim: [ 256 ]
            input_dim: 384 # 128 * 3

      in_head: 256

      anchor_number: *anchor_num
      dir_args: *dir_args
    m3:
      model_dir: stage0_m3_collab
      core_method: *core_method_m3
      sensor_type: *sensor_type_m3
      local_dim: &local_dim_m3 64

      encoder_args:
        voxel_size: *voxel_size_m3
        lidar_range: *cav_lidar
        mean_vfe:
          num_point_features: 4
        spconv:
          num_features_in: 4
          num_features_out: 64
        map2bev:
          feature_num: 128

      backbone_args:
        layer_nums: [3]
        layer_strides: [1]
        num_filters: [64]
        inplanes: 128
  
      aligner_args:
        core_method: identity
      
      adapter_args: 
        local_dim: *local_dim_m3
        local_range: *cav_lidar
        protocol_parameters:
          protocol_dim: *protocol_dim
          # Compute from: H_uni: 128, W_uni: 256; unify_range: [-102.4, -51.2, -3, 102.4, 51.2, 1]
          granularity_H: *gra_H
          granularity_W: *gra_W
        resizer:
          method: conv  # 通道数不一致时的对齐方式
          reduce_raito: 2 
        momentum_ratio: 0.8
        encoder:
          num_layers: 2
          num_heads: 2
          d_ff: 128
          d_model: *protocol_dim
          dropout: 0.2
        decoder:
          num_layers: 1
          num_heads: 2
          d_model: *local_dim_m3
          d_ff: 128

      fusion_net:
        method: pyramid
        args: 
          resnext: true
          layer_nums: [3, 5, 8]
          layer_strides: [1, 2, 2]
          num_filters: [64, 128, 256]
          upsample_strides: [1, 2, 4]
          num_upsample_filter: [128, 128, 128]
          anchor_number: *anchor_num

          shrink_header: 
            kernal_size: [ 3 ]
            stride: [ 1 ]
            padding: [ 1 ]
            dim: [ 256 ]
            input_dim: 384 # 128 * 3

      in_head: 256

      anchor_number: *anchor_num
      dir_args: *dir_args
    m4:
      model_dir: stage0_m4_collab
      core_method: *core_method_m4
      sensor_type: *sensor_type_m4
      local_dim: &local_dim_m4 64

      encoder_args:
        anchor_number: *anchor_num
        grid_conf: *grid_conf_m4
        data_aug_conf: *data_aug_conf_m4
        img_downsample: 8
        img_features: 128
        use_depth_gt: false
        depth_supervision: true
        camera_encoder: Resnet101

      camera_mask_args:
        cav_lidar_range: *cav_lidar
        grid_conf: *grid_conf_m4

      backbone_args:
        layer_nums: [3]
        layer_strides: [2]
        num_filters: [64]
        inplanes: 128

      aligner_args:
        core_method: identity

      adapter_args: 
        local_dim: *local_dim_m4
        local_range: *cav_lidar
        protocol_parameters:
          protocol_dim: *protocol_dim
          # Compute from: H_uni: 128, W_uni: 256; unify_range: [-102.4, -51.2, -3, 102.4, 51.2, 1]
          granularity_H: *gra_H
          granularity_W: *gra_W
        resizer:
          method: conv  # 通道数不一致时的对齐方式
          reduce_raito: 2 
        momentum_ratio: 0.8
        encoder:
          num_layers: 2
          num_heads: 8
          d_ff: 128
          d_model: *protocol_dim
          dropout: 0.2
        decoder:
          num_layers: 1
          num_heads: 8
          d_model: *local_dim_m4
          d_ff: 128

      fusion_net: 
        method: pyramid
        args:  
          resnext: true
          layer_nums: [3, 5, 8]
          layer_strides: [1, 2, 2]
          num_filters: [64, 128, 256]
          upsample_strides: [1, 2, 4]
          num_upsample_filter: [128, 128, 128]
          anchor_number: *anchor_num

          shrink_header: 
            kernal_size: [ 3 ]
            stride: [ 1 ]
            padding: [ 1 ]
            dim: [ 256 ]
            input_dim: 384 # 128 * 3

      in_head: 256

      anchor_number: *anchor_num
      dir_args: *dir_args


loss:
  core_method: pnpda_loss_protocol
  args:
    contrastive:
      tau: 0.1
      max_voxel: 30

    pos_cls_weight: 2.0
    cls:
      type: 'SigmoidFocalLoss'
      alpha: 0.25
      gamma: 2.0
      weight: 1.0
    reg:
      type: 'WeightedSmoothL1Loss'
      sigma: 3.0
      codewise: true
      weight: 2.0
    dir:
      type: 'WeightedSoftmaxClassificationLoss'
      weight: 0.2
      args: *dir_args
    depth:
      weight: 1.0
    pyramid:
      relative_downsample: [1, 2, 4]
      weight: [0.4, 0.2, 0.1]

